### ISSUE TITLE
🚀 `tirith/cli.py`: version should be taken from `__init__.py` not redefine it

### ISSUE THREAD

**Issue by refeed** [StackGuardian/tirith#110]
**Is your feature request related to a problem? Please describe.**
Nope, just an enhancement.

**Describe the solution you'd like**
When bumping the version, we generally need to search the string of current version in all files and replace it with the new version. Ideally, there should be only one place to change, i.e. one definition of the version, then the other modules that wants to use the version just need to reuse the definition and not redefine it.

One example of this is:
![image](https://user-images.githubusercontent.com/20320125/236098284-0ecbe746-faaf-4018-9cce-daa31e33a7d8.png)

The definition of version in `cli.py` could be easily replaced with the definition from `__init__.py`

**Comment by ANISH-SR** [comment]
Hi Sir,
I'm interested in solving this issue. Could you please assign it to me?

**Comment by ANISH-SR** [comment]
#142

**Comment by samriddhi99** [comment]
Fixed by #142
