### ISSUE TITLE
Update logger initialization to use module-specific loggers

### ISSUE THREAD

**Issue by samriddhi99** [StackGuardian/tirith#140]
Currently, tirith uses logger = logging.getLogger() to create logger objects in various modules. This approach uses the root logger, which is not ideal as it lacks context about where the logging messages are coming from. We should update these instances to use logger = logging.getLogger(__name__), which will create a logger named after the module. 

Tasks:
- [ ] Search for all instances of logger = logging.getLogger() in the codebase.
- [ ] Replace logger = logging.getLogger() with logger = logging.getLogger(__name__).
- [ ] Ensure all logging messages continue to work as expected.
- [ ] Run tests to confirm that no existing functionality is broken by this change.

**Comment by chetak123** [comment]
I would like to take this up please.

**Comment by AkashS0510** [comment]
Have resolved the issue. Kindly review the PR.

**Comment by samriddhi99** [comment]
Closed by Pr #143
