### ISSUE TITLE
Convert all variable and attribute names from camelCase to snake_case

### ISSUE THREAD

**Issue by refeed** [StackGuardian/tirith#174]
There are some usages of camelCase in our codebase, as a Python project, it's better to stick to the convention of using the `snake_case` just for consistency.

This task is about converting all of those variables that's in camelCase to snake_case

**Comment by tejasvi541** [comment]
Hey Rafeed, I would like to contribute towards this issue, thanks

**Comment by refeed** [comment]
Hi @tejasvi541 , thanks for your interest, just assigned you

**Comment by refeed** [comment]
Hi @tejasvi541, is there any followup to this?

**Comment by tejasvi541** [comment]
Hi @refeed, onto it almost, would create a pull request asap
