### ISSUE TITLE
Create a dev container to make development easier 

### ISSUE THREAD

**Issue by refeed** [StackGuardian/tirith#175]
**Is your feature request related to a problem? Please describe.**
Usually new developers, they have a hard time for contributing especially the first time because they need to set up their own development environment. The current process might look simple, but in reality it's much more complex than that, one of the most often problems that I encountered when doing this kind of setup is OS difference, people using Windows will have a different steps of setting it up with those who are using Linux based distro or even Mac.

**Describe the solution you'd like**
Dev container has been around for sometime to solve this problem. 

**Describe alternatives you've considered**
Another way is using vagrant to spin up a VM inside the contributor's machine, but this is not preferable as it is consuming too much resources compared to dev container.

**Additional context**
No

**Comment by AkashS0510** [comment]
@refeed Kindly assign this to me
