### ISSUE TITLE
Add PR Template and General Issue Template

### ISSUE THREAD

**Issue by samriddhi99** [StackGuardian/tirith#179]
It would be helpful to add the following templates to this repository to ensure consistency and improve the quality of both PRs and issues:

#### 1. Pull Request (PR) Template:
A PR template will guide contributors to provide the necessary information when opening a PR, such as:
- What changes are being made
- Why the changes are necessary
- What effects those changes have
- Any related issues or tickets
- Testing

It is also recommended to have a checklist that looks like this:
- **Checklist:**
  - [ ] Code has been linted.
  - [ ] Documentation has been updated (if needed).
  - [ ] Tests have been added or updated (if needed).

#### 2. General Issue Template:
Tirith already has templates for bug reports and feature requests. It would be useful to introduce a general issue template for cases that don't fall into either of those categories.

The template should include:
- Provide a detailed description of their issue.
- Outline any expected or unexpected behaviors observed in the code.

**Comment by Denish3436** [comment]
@samriddhi99 I would like to work, can you please assign me....

**Comment by Denish3436** [comment]
I Really apologies for above closed PR....
