### ISSUE TITLE
🚀 Fix Error Messages with Extra Closing Parentheses

### ISSUE THREAD

**Issue by AkashS0510** [StackGuardian/tirith#182]
Issue: Some functions like `direct_dependencies_operator function` in the `handler.py` has error messages that include an extra closing parenthesis.

Task: Look through the error messages. Remove the redundant closing parenthesis to correct the error messages.

**Comment by Denish3436** [comment]
I would like to work on this, can you assign me

**Comment by AkashS0510** [comment]
@zafar-hussain Just to follow up what's your update on this?

**Comment by Denish3436** [comment]
@AkashS0510 Any update??

**Comment by zafar-hussain** [comment]
> @zafar-hussain Just to follow up what's your update on this?

sorry @AkashS0510 , please do assign this issue to another applicant,

thanks
