### ISSUE TITLE
 Add NotContains evaluators, etc

### ISSUE THREAD

**Issue by AkashS0510** [StackGuardian/tirith#206]
Add NotContains evaluators, etc (see [https://www.checkov.io/3.Custom Policies/YAML Custom Policies.html](https://www.checkov.io/3.Custom%20Policies/YAML%20Custom%20Policies.html) in "Attribute Condition: Operators" section)

Most Important:

- NotContains

Additions:

[https://www.checkov.io/3.Custom Policies/YAML Custom Policies.html](https://www.checkov.io/3.Custom%20Policies/YAML%20Custom%20Policies.html)

**Comment by refeed** [comment]
Already solved
https://github.com/StackGuardian/tirith/blob/main/src/tirith/core/evaluators/not_contains.py
