### ISSUE TITLE
🚀 prettyprinter.py: Delete "Results" text in the result

### ISSUE THREAD

**Issue by refeed** [StackGuardian/tirith#92]
**Is your feature request related to a problem? Please describe.**
This is more to an enhancement, I'd like to see what other maintainer think of this.
![image](https://user-images.githubusercontent.com/20320125/204458702-98db2bf1-a0f4-4539-883b-0e4c20ce1c69.png)
So, when we run a tirith check, when it failed, most of the text will be shown as red, but there's a white text that mention "Results" right in the middle of the "FAILED" string and the list of the results below it.

**Describe the solution you'd like**
I think it can be deleted, as I think the user would already know that the text below "FAILED" or "PASSED" is the list of results

**Comment by ANISH-SR** [comment]
Hi Sir, 
I would like to work on this issue. Can you please assign it to me?

**Comment by refeed** [comment]
Sure, assigned

**Comment by refeed** [comment]
Closed by https://github.com/StackGuardian/tirith/pull/141
